{% set version = "3.1.0" %}
{% set sha256 = "7801c05c290adaf857b714fc1d54dd3823d32fdcafa704d525d5654f5ca4e426" %}
{% set openjdk_version = "11.0.*" %}

package:
  name: denoptim
  version: {{ version }}

source:
  url: https://github.com/denoptim-project/DENOPTIM/archive/refs/tags/v3.1.0.zip
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - openjdk =={{ openjdk_version }}
    - maven
  run:
    - openjdk =={{ openjdk_version }}

test:
  commands:
    - denoptim -v

about:
  home: https://github.com/denoptim-project/DENOPTIM
  license: AGPL-3.0-only
  license_file: LICENSE.txt
  summary: 'Package for de novo design and virtual screening of functional molecules of any kind.'
  description: Package for de novo design and virtual screening of functional molecules of any kind.
  dev_url: https://github.com/denoptim-project/DENOPTIM
  doc_url: https://github.com/denoptim-project/DENOPTIM

extra:
  recipe-maintainers:
    - marco-foscato
